@baseUrl = http://localhost:3333
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMGRhNDE0MC1jZjc3LTQ2ZDktOTk1NS0wODZiOTg0Nzc2MDciLCJpYXQiOjE3Mjk3OTg4NTd9.fWXwLq7qe997VKH5LWJUPxoa2sy7YwU_TXiTKJy-xtD-u9lWr1AxRKjkWThZwD_DCT6b_Vu4abvACIK9li721xw61CeZOY_oP_Nw9ib4WMjTo272xg7Err4-uC-y-JV0XGBNh78M4o8qxvYu1VLgTZuGTkyeeY9MAazBktSr8IfT7gT-sdb1NRPPYSHR2VeVE31cqHvgme_7cwEXodN-B-Lpq6sii7tBfRBl-FJonA33Xn4nEEbirFpIDOaXeJcKC9l0NpM0zYZV2bzbz1eRDbj8695qv7HcnR27_Ggqy7K2KlW2W57R1JM_FeOADq3eiGSuxQ7krqpk9APwOy7IFQ

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json
{
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 5",
  "content": "Teste"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}