@baseUrl = http://localhost:3333
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMGRhNDE0MC1jZjc3LTQ2ZDktOTk1NS0wODZiOTg0Nzc2MDciLCJpYXQiOjE3MzAxMzY5MTh9.phHd6vLEYIfpPhXdtW216EgDH3jpfx7fu7ksm1-aSSV3_oNE2cwJ76kc2Qz13Vf4i4gAR023smnc0os7SDiNytlUvm_X2Sz-SVi8u09OYR1FpmGqHHXu7uvh052aPZxzxKw05PYm-7y7IA4N8v6lLVXJZqZY7qYz_w3VksYrJJP2fpftRTutqrGeTt9COnz7PXwDvjTmmdAOURI8Y4WTxlc0ny2Fwjz0OI-DSYoEB6PBMNX-hGjQzHGcxNPAEVxU0ySVMpdjyxA7WRCYSxukUSC4byjsYkYYh7FvKUlUYKLqgD4_uf-FTJnypqENMGmJndlzD3p8Pqr4p8j9Zic4DQ

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 6",
  "content": "Teste"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}